### ISSUE TITLE
Error at terminal

### ISSUE THREAD

**Issue by AristoSocrates** [Destaq/life-calendar#3]
I'm running Mac OS. I have the latest version of Python and PostgreSQL installed.

As per instructions, under "Automatic Method: Shell Command", I right clicked the downloaded folder and selected "New Terminal at Folder". Then, I pasted the command "source setup.sh". 

It began to install but came up with the following errors: 

- ERROR: Command errored out with exit status 1:
- Error: pg_config executable not found.
- ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

What do these mean? How do I bypass this? I don't know much about coding but can troubleshoot from instructions so I'd appreciate some advice.

**Comment by Destaq** [comment]
I'm sorry, I'm not sure how I missed this. Anyway, there seem to be two problems with your installation attempt.

1. It seems like you didn't configure PostgreSQL fully. Please see [here](https://stackoverflow.com/a/24645416/12876940).
2. Does `python -V` return Python 2.X.X? (Some version of 2.) If so, try modifying the `setup.sh` file to use `python3` instead of `python`. Otherwise, I'm afraid there's not enough to go off of.

Since these seem to be installation issues on your local machine, rather problems with the project, I'm closing for now.
